### ISSUE TITLE
cannot get information or connection to router

### ISSUE THREAD

**Issue by caplinux** [respawner/looking-glass#71] opened 2019-05-22 22:32 UTC
Hi have this error but the have log's

Error! No parameter given.

[2019-05-22 21:26:10] [client: 192.168.x.x] route-server.gblx.net > [BEGIN]  show bgp ipv4 unicast 8.8.8.8
[2019-05-22 21:26:10] [client: 192.168.x.x] route-server.gblx.net > [END]  show bgp ipv4 unicast 8.8.8.8

 [22/May/2019:17:26:10 -0400] "POST /looking-glass/execute.php HTTP/1.1" 200 - "http://192.168.30.110/looking-glass/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"

**Comment by respawner** [comment] 2019-05-23 21:18
Can you give the following details?

1. version of the looking glass
2. type of the router

**Comment by caplinux** [comment] 2019-05-24 15:46
Hello, 

1. Looking Glass 2.0.1
2. Cisco Switch and Cisco Router

**Comment by respawner** [comment] 2019-05-24 17:16
The logs do not show any error? Can you describe how to reproduce the issue?

**Comment by caplinux** [comment] 2019-05-27 15:05
I try to send command ping, tracert, show route and the log say: Error! No parameter given.

**Comment by respawner** [comment] 2019-05-27 15:14
Can you show a screenshot of the issue?

**Comment by caplinux** [comment] 2019-05-27 15:46
![image](https://user-images.githubusercontent.com/4305655/58429797-a4219b80-806c-11e9-9d6d-abe33137fe6c.png)

**Comment by respawner** [comment] 2019-05-28 17:44
I don't have a IOS based router myself and stable releases should be pretty mature and do not have such a bug. It's possible that I'm missing something though. Did you try using the bleeding edge code from the git repository?

**Comment by caplinux** [comment] 2019-05-31 13:31
Hi, I used git clone a few days ago, I think is stable version.

**Comment by respawner** [comment] 2019-06-18 20:19
Closing as I'm unable to reproduce the issue with the latest commit (1735bf3 as of today).

**Closed by respawner** 2019-06-18 20:19 UTC
